version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      python-project:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /.github/requirements
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      python-ci:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
