[files]
extend-exclude = [
  ".git",
  ".mypy_cache",
  ".pytest_cache",
  "build",
  "dist",
  "reports",
]

[default.extend-words]
H234598 = "H234598"
adresse = "adresse"
ba = "ba"
egal = "egal"
ist = "ist"
lauch = "lauch"
lokale = "lokale"
Lokale = "Lokale"
normale = "normale"
Normale = "Normale"
oder = "oder"
ser = "ser"
transkript = "transkript"
transkription = "transkription"
variante = "variante"
