[files]
extend-exclude = [
  ".git",
  ".mypy_cache",
  ".pytest_cache",
  "build",
  "dist",
  "reports",
]

[default.extend-words]
H234598 = "H234598"
adresse = "adresse"
ba = "ba"
ist = "ist"
ser = "ser"
